# Generated by Django 3.1.7 on 2021-03-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
