# Generated by Django 3.1.7 on 2021-03-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('product', '0003_remove_product_expiration_date'),
        ('stock_entry', '0002_stockentry_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
        ),
    ]
