# Generated by Django 3.1.7 on 2021-03-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_remove_product_expiration_date'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField()),
                ('quantity', models.IntegerField()),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
            options={
                'verbose_name': 'Stock Exit',
                'verbose_name_plural': 'Stock Exit',
                'db_table': 'stock_exit',
            },
        ),
    ]
