# Generated by Django 3.1.7 on 2021-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=13)),
                ('unit_of_measure', models.CharField(max_length=30)),
                ('level_minimum', models.IntegerField()),
                ('cost_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reated', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produtc',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
