# Generated by Django 3.1.7 on 2021-03-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
    ]
