# Generated by Django 3.1.7 on 2021-03-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20210309_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(default=-1.0, max_length=250),
            preserve_default=False,
        ),
    ]
