# Generated by Django 3.1.7 on 2021-03-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_provider_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='area_code',
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
